// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HSVSelector: typeof import('./src/components/HSVSelector.vue')['default']
    RGBSelector: typeof import('./src/components/RGBSelector.vue')['default']
  }
}
